version: '2'
services:
  api-cassandra:
    image: cassandra:3.11.5
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
  api-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: api-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
